name: 锁艺人签到

on:
    workflow_dispatch:
    schedule:
        - cron: 4 10,22 * * *

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 18
              uses: actions/setup-node@v1
              with:
                  node-version: 18
            - name: npm install
              run: |
                  npm install
            - name: "运行 锁艺人签到脚本"
              run: |
                  node main.js
              env:
                  SYRID: ${{ secrets.SYRID }}
                  SYRPWD: ${{ secrets.SYRPWD }}
                  NOTIFY: ${{ secrets.NOTIFY }}
